### ISSUE TITLE
Multimodal loader doesn work

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#109]
due to #108

**Comment by nicwade** [comment]
The error is in the process file not the framework.  Ensure in/out_datasets are passed as lists of strings, not string

**Comment by aaron-parsons** [comment]
Re-opening this, since the bug still is there. At least on my computer and on the build.

We can talk about this at a computer sometime.

I think this is a problem actually with the way the configurator sees strings. It passes them as unicode objects which means that when the plugin runs, no data object is returned.

**Comment by aaron-parsons** [comment]
Now we talked, I've updated the test and it now works:-)
