### ISSUE TITLE
check deepcopy on data object is working correctly

### ISSUE THREAD

**Issue by nicwade** [DiamondLightSource/Savu#110]

**Comment by markbasham** [comment]
Made some updates to this so the deepcopy on raw tomo is better, still needs some work though to get it working.

**Comment by nicwade** [comment]
Have you made some changes to the tomoRaw case?  My own changes have not
yet been pushed as I hadn't quite finished.  Also, this ticket relates to
the copying of the data object, not tomoRaw...
