### ISSUE TITLE
Something is not right with the reconstructed images

### ISSUE THREAD

**Issue by markbasham** [DiamondLightSource/Savu#116]
After the first set of reconstructions i did, there now seems to be an issue with the reconstruction in that it looks like it is not being run over the correct angles.  All the reconstructions have the same issue, so i think it must be in base recon, or how the angles are being passed about.  The change has happened since the 21st of sept.  The effect seems to not show too much in the example data, but i do think the quality has dropped slighly.

Sorry for a poor ticket, but im not sure where the issue is.

**Comment by nicwade** [comment]
I've changed some things. Can you try reconstructing again and let me know if there is still the same issue :-)

**Comment by markbasham** [comment]
Tried, but couldent get anything to run, looks like im getting the same metadata problem as Aaron.  I have pushed some simple fixes up.

**Comment by nicwade** [comment]
Probably shouldn't have tried to change things whilst doing the training
course.  I had to stop copying metadata temporarily because data patterns
were being over-written this way. The intention is to fix this today - I
didn't think it would affect the tomography stuff, but it will be deleting
the centre of rotation I guess...

**Comment by markbasham** [comment]
No worries, it was the rotation angles which caused the problems for me.

Sent from my HTC

----- Reply message -----

**Comment by nicwade** [comment]
I've checked basic_tomo_process on the test data and the output looks ok now so I think this is fixed.  Closed the ticket but please re-open if your data doesn't look right.

**Comment by markbasham** [comment]
Yep now a couple of other fixes are in, it all works perfectly :)
