### ISSUE TITLE
metadata has ceased to be copied through the pipeline

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#119]
When running simple_fit_test the pipeline now fails in the SimpleFit plugin.

The plugin is expecting to have something in metadata called PeakIndex, which isn't there.

However, PeakIndex is set in the previous plugin.

Nic, you may well already know about this as I guess it's a continuation of the earlier bug.

**Comment by markbasham** [comment]
I see this too with the tomography pipeline.
