### ISSUE TITLE
support for 3 dimensional scans

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#144]
Currently we expect 2 translational motors, one of which is fast. If we have only 1, then the code breaks.

I believe this is in data_structures line 453

**Comment by nicwade** [comment]
If this already works (by adding dimension of length 1) and you are happy with it, I don't think it is worth changing underneath, as I had a look and it is done quite neatly.  Please move this to the 'Done' pile if you agree.

**Comment by aaron-parsons** [comment]
Sorry, no I don't agree. It's fine for now, but I wouldn't class this as fixed. It currently requires the user to rewrite their file, or for us to have a different loader for each different scanning dimensionality. Long term we should have a flag that gets set for this in the loader, however some backend support will be needed since we can't actually change the data itself, so the slice list needs modding. The reason why I'm a bit insistent about this is that most people (Steve currently, I14 eventually, I13 currently, I08 currently...) record their data like this. I currently rewrite it into a readable form. It's an edge case, but an important one for scanning. Sorry! 

We don't need an urgent fix, but a future one.

**Comment by nicwade** [comment]
I'm unsure of a few things.  Firstly, why do you require a different loader for data with different dimensionality?  Why does I13 only collect single sinogram data?  If it is that they output each sinogram to a different hdf5 file then that is not currently compatible with the savu framework.  A different data class would be required to stitch them all together.  Something we have discussed but not implemented (see ticket 65).

**Comment by aaron-parsons** [comment]
This will be fixed with the upgrade to using virtual dataset. For now a file converter is used before using the data with savu.
