### ISSUE TITLE
process list editor doesn't warn user when exiting without saving

### ISSUE THREAD

**Issue by srikanthnagella** [DiamondLightSource/Savu#174]
After use had made changes to the values in the process list editor and use exit command without save command. it will be nice  to warn user that the modifications will not be saved

**Comment by markbasham** [comment]
Aslo would be nice to add a "Confim save option"

**Comment by rcatwood** [comment]
breaks all my scripts.

**Comment by aaron-parsons** [comment]
Why are you scripting the configurator?

**Comment by rcatwood** [comment]
Is there another way?

**Comment by aaron-parsons** [comment]
What are you trying to do?

**Comment by markbasham** [comment]
You should be able to add some 'Y' to your script to get round this.  after saving and exiting.

**Comment by rcatwood** [comment]
Hi,Aaron

The information obtained by another program looks roughly like this:
Where in some other occasion the columns may vary (ImageJ )

Input file and process list on /dls/tmp/savu_bug_data/scripting/

Unfortunatley the proper data is on /dls/archive/i12/data/2015/ee13236-1/processing/frames/ for now 

 
 1 Scan    Index   Area    Mode    Min     Max     X       Y       XM      YM      BX      BY      Width   Height  Slice   CoR
  2 55513   1       1196293 3224    2104    58369   1263.735        1064.732        1250.968        1051.64 711     512     1102    1111    1       512.35
  3 55517   2       1195593 3608    1998    57112   1264.364        1068.18 1259.068        1062.904        710     513     1103    1109    2       512.85
  4 55538   3       1044379 2589    1096    34268   1298.463        899.77  1338.103        938.209 736     431     1126    936     3       486.41
  5 55540   4       1044621 2562    1186    33892   1299.002        899.93  1337.036        931.111 736     431     1126    936     4       485.74
  6 55564   5       1044447 2562    1205    36131   1299.185        899.741 1292.079        924.731 736     431     1126    936     5       515.22
  7 55572   6       1044923 2562    1373    35708   1299.56 900.336 1295.291        922.783 736     431     1127    936     6       514.38
  8 55598   7       1727928 2562    1436    44853   1299.219        900.113 1300.212        910.398 510     348     1576    1105    7       705.05
  9 55604   8       1727593 2562    1418    51439   1299.74 900.075 1396.39 898.556 511     348     1575    1105    8       702.65
 10 55606   9       1725706 15000   1310    36569   1299.304        900.173 1287.681        908.231 511     348     1574    1105    9       704.05
 11 55628   10      1614049 15976   2763    52225   1282.569        899.429 1362.057        902.351 546     348     1471    1105    10      676.18
 12 55630   11      1613986 16024   2576    49736   1282.837        899.732 1349.371        902.433 547     348     1471    1105    11      673.54

...

33 56003   32      1425319 2562    1134    31188   649.746 1369.236        655.839 1353.396        51      769     1197    1203    32      540.13


The input dataset -- eg scan 55701:

ls /dls/archive/i12/data/2015/ee13236-1/processing/frames/55701/
55701_000.nxs  55701_003.nxs  55701_006.nxs  55701_009.nxs  55701_012.nxs  55701_015.nxs  55701_018.nxs  55701_021.nxs  55701_024.nxs  55701_027.nxs  55701_030.nxs
55701_001.nxs  55701_004.nxs  55701_007.nxs  55701_010.nxs  55701_013.nxs  55701_016.nxs  55701_019.nxs  55701_022.nxs  55701_025.nxs  55701_028.nxs
55701_002.nxs  55701_005.nxs  55701_008.nxs  55701_011.nxs  55701_014.nxs  55701_017.nxs  55701_020.nxs  55701_023.nxs  55701_026.nxs  55701_029.nxs

The input data may be cropped to (BX,BY) .. (BX+Width, BY+Height), minus a safety margin. (which was 25 in X and 0 in Y) 

The CoR is the centre of rotation in some unclear coordinate system (cropped?? another ongoing issue....)

It is implemented by this section of BASH:

26 trimx=25
....

 35       words=($a)
 36       SCANNAME=${words[0]}
 37       bx=${words[10]}
 38       by=${words[11]}
 39       ww=${words[12]}
 40       hh=${words[13]}
 41       cor=${words[15]}
 42       (( xstart = $bx + $trimx ))
 43       (( xend = $bx + $ww -  $trimx ))
 44       (( ystart = $by ))
 45       (( yend = $by + $hh  ))
 46       (( yhalf = ( $yend + $ystart ) / 2 ))
 47       (( yhend = $yhalf + 1 ))
 48       echo "scan $SCANNAME cropped [$xstart:$xend,$ystart:$yend]"
 49       savustring="['0:end:1:1', '$ystart:$yend:1:1', '$xstart:$xend:1:1']"
 50       echo "savu crop string is"
 51       echo "$savustring"

.. folder generation stuff ..

 74       echo "getting the settings file"
 75       echo -e "open ${savufile}\nmod 1.1 $savustring\nmod 7.2 $cor\nsave\nexit" | python $SAVUHOME/scripts/config_generator/savu_config.py
 76       echo "saved  $savufile"

.. more folder generation stuff... 

Apply to all frames of the scan: 

 82 cat > $qscript <<-EOF 
 83 #!/bin/bash
 84 set -x
 85 module add savu-fork
 86 source activate savu_mpi1
 87
 88 (( idx = \$SGE_TASK_ID - 1 ))
 89 FRAMENUM=\$idx
 90 framebase=\`printf "${SCANNAME}_%03d" \$FRAMENUM\`
 91 framename=\$framebase.nxs
 92 projnexus=$projfolder/\$framename
 93 echo "projnexus is \$projnexus"
 94
 95 outroot=$outscan/\$framebase
 96 tmproot=$tmpscan/\$framebase
 97
 98 mkdir -p \$outroot
 99 mkdir -p \$tmproot
100
101 python \$SAVUHOME/savu/tomo_recon.py \$projnexus $savufile \$tmproot -n GPU
102
103 EOF
104

-- 
This e-mail and any attachments may contain confidential, copyright and or privileged material, and are for the use of the intended addressee only. If you are not the intended addressee or an authorised recipient of the addressee please notify us of receipt by returning the e-mail and do not use, copy, retain, distribute or disclose the information in or attached to the e-mail.
Any opinions expressed within this e-mail are those of the individual and not necessarily of Diamond Light Source Ltd. 
Diamond Light Source Ltd. cannot guarantee that this e-mail or any attachments are free from viruses and we cannot accept liability for any damage which you may sustain as a result of software viruses which may be transmitted in or with the message.
Diamond Light Source Limited (company no. 4375679). Registered in England and Wales with its registered office at Diamond House, Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11 0DE, United Kingdom

**Comment by aaron-parsons** [comment]
Thanks Robert. I’ll look into it now.

Having tools like this would also help I18 and also I13 coherence at least.

Aaron
