### ISSUE TITLE
Document: small mismatch in behaviour (as seen by user rcatwood)

### ISSUE THREAD

**Issue by rcatwood** [DiamondLightSource/Savu#182]
The instruction:

`git pull upstream`

Gives me this message:

```
You asked to pull from the remote 'upstream', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.

```

I have to specify ‘git pull upstream master’ (or some other branch) for the pull operation to work.

I expect it works as written if you are logged in as the **DiamondLightSource** administrator user but not a 'normal' user?

**Comment by markbasham** [comment]
Hi Nic,

probably best if you fix this one, should be a one liner, but I guess check that it still works.

**Comment by markbasham** [comment]
Had a quick look and will fix this
