### ISSUE TITLE
GPU reconstruction fills up the GPU memory after processing a couple of gigabytes

### ISSUE THREAD

**Issue by rcatwood** [DiamondLightSource/Savu#183]
Processing a 7gb file with significant cropping (/dls/tmp/savu-data) using GPU , not using MPI version at all, fails due to the GPU memory filling up. 

This was tried first on i12-ws011 and then on com07-04 to be sure that the GPU used for display didnt' cause the problem. Each of these has a 6GB gpu , QUADRO

Excerpt from the console output:

Image size to read : sizex 1128 sizey 830 imagesize 936240 batchsize 79580400
thisbatch 85
FBP_CUDA
FBP_CUDA
Error: Cuda error: out of memory

real    6m58.326s
user    5m16.379s
sys     1m27.550s

Excerpt from user.log:

2016-02-17 12:45:24,297 - FBP_CUDA -  32% complete
2016-02-17 12:45:24,520 - FBP_CUDA -  32% complete
2016-02-17 12:45:24,742 - FBP_CUDA -  32% complete
2016-02-17 12:45:24,966 - FBP_CUDA -  32% complete
2016-02-17 12:45:25,189 - FBP_CUDA -  33% complete
2016-02-17 12:45:25,411 - FBP_CUDA -  33% complete
2016-02-17 12:45:25,635 - FBP_CUDA -  33% complete
2016-02-17 12:45:25,857 - FBP_CUDA -  33% complete

Last NVIDIA_SMI output before job failed:

==============NVSMI LOG==============

Timestamp                           : Wed Feb 17 12:45:25 2016
Driver Version                      : 352.41

Attached GPUs                       : 2
GPU 0000:11:00.0
    FB Memory Usage
        Total                       : 5375 MiB
        Used                        : 10 MiB
        Free                        : 5365 MiB
    BAR1 Memory Usage
        Total                       : N/A

**Comment by rcatwood** [comment]
Quadro on the workstation and Tesla on the cluster node.

**Comment by rcatwood** [comment]
This is happening because the astra reconstruction plugin repeatedly creates astra objects, the  equivalent to allocating memory repeatedly inside a function. The astra functions are outside the scope of the Python garbage collection since it calls the Astra library written in C++ or similar.  For this reason and for performance, the objects should be allocated once (i.e. in setup function ) and re-used , then deleted once (i.e. in cleanup function)  -- the geometry and algorithm objects don't need to change.  This should not be managed by deleting the object each time -- the overhead is significant , the creation of the object not only allocates the memory but calculates the matrix and also invokes the fftw planning operation, these take a noticeable amount of time for realistic size tomography data.

**Comment by nicwade** [comment]
Thanks for the info!  The geometry doesn't change if the centre is the same for all sinograms, but for the case where it is not I had to leave the geometry setup inside the main function.  No good if it doesn't work of course.

I notice that I had forgotten to call astra_delete() at the end of the main processing, which may fix the problem.  If the (partly developed) 3D vectorised geometry works for 2D geometries then this will enable the geometry to be created in the pre_process regardless of centre.

**Comment by rcatwood** [comment]
Rather, the centre changes so therefore the shifting of the data changes to bring the centre to the middle. The projection geometry does not need to change. I see that some calculation may need to be done including the entire vector of CoR’s at first , to fix the maximum required padding dimension? I can’t quite follow how array_pad works , it seems like it should be operating on the vector of CoR’s but it also gets called all the time.  The range of CoR should be very small or else we have points rising out of the row and then  image rotation should be applied to correct the tilt, rather than centre shifting. Not sure how small but I think a few pixels max, so the ‘extra padding’ required to ensure that all padded sinograms have the same width would be minimal.

A new sinogram can be put into an existing  object using the ‘store’ method in ASTRA as far as I recall.



Other than not working .. its really good! :)

**Comment by nicwade** [comment]
We pad the data so the centre of the sinogram is the centre of rotation.  So the size of the sinogram changes, if the centre changes, and the size of the sinogram is required to create the projection geometry.  Hopefully I will be able to just use the vectorized case.
