### ISSUE TITLE
Amend string in shape error

### ISSUE THREAD

**Issue by nicwade** [DiamondLightSource/Savu#198]
Can be found in a plugin used by test i18_xrd_pipeline_test.py.  We should investigate after the release.

**Comment by aaron-parsons** [comment]
Is this still an issue?

**Comment by nicwade** [comment]
See i18_xrd_pipeline_test.py

**Comment by nicwade** [comment]
The new test doesn't give the error though.

**Comment by aaron-parsons** [comment]
Cool. I'll close it then.
