### ISSUE TITLE
"Metadata only" operations

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#224]
Sometimes (particularly for post processing of clusters), it would be useful to have an operation that goes through the data frame by frame as always, and then just assigns a metadata label to each frame. No data is output, but the process would still take big data, and be data-parallel.

I think at the moment we must output data, which means duplicating the dataset. Which is a bit of a waste of memory and not the most performant thing to do.

Is there anyway I could set a flag, and then instead of being copied, the data gets linked in the output file instead? Since it is a replica.

**Comment by nicwade** [comment]
Just going through old tickets and you probably know this already.  You can output a very small dataset (you don't need to duplicate the input), e.g. one value per frame and use the 'remove' flag when creating it (in the setup method) that tells the framework not to hold onto the data after the plugin has completed.  You can then use post_process method to put this data into the meta_data.  See vo_centering for an example of this.
