### ISSUE TITLE
Can I have an output/input that is an array of strings?

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#244]
This is maybe a stupid question, anbd certainly isn't essential, but in numpy I can create an array-like that can contain pointers to any kind of object.

The output of my fitting can give a message as to what caused it to stop/criteria for convergence etc... which is a string. So can I set the dtype to be object where the object is a string? The output would be a sinogram but where each point has strings.

I will probably try it at some point, but was just curious if there is a fundamental reason why this wouldn't work.

**Comment by nicwade** [comment]
There is a keyword you can pass to the create_dataset function in setup()
that allows you to set the dtype of the numpy array.  Have a look at the
index.html document (I think) I sent you. Search for 'create_dataset' and
you can get the full information there.

**Comment by aaron-parsons** [comment]
Excellent. Thanks!

Aaron

#####################
Aaron Parsons
Data Analysis Scientist
I14: Hard X-ray Nanoprobe
Diamond Light Source
Harwell Science and Innovation Campus
Didcot
Oxfordshire
OX11 0DE

Phone:+44 (0) 123577 x8805
#####################
________________________________
