### ISSUE TITLE
Is the travis version of scipy really 0.9.0?

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#247]
Currently the strip_background test fails on travis (passes locally) due to not being able to import savgol_filter from scipy.signal

On the travis log it says 
python-scipy (0.9.0+dfsg1-1ubuntu2) 

If I module load scipy/0.9.0 at Diamond, it also breaks if I try the import.

If I'm not barking up the wrong scipy, could we update it to 0.17.0?

**Comment by markbasham** [comment]
yes but now it isnt :)

**Comment by aaron-parsons** [comment]
Legend. Ta
