### ISSUE TITLE
Turn disp off in configurator on parameter change

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#271]
When you modify a parameter in a process list in the configurator, the default at the moment is to redisplay the updated process list to the screen. This is really annoying when your process list is several pages long. Could we default it to off? Users can type disp to view it when they want.

Ta

**Comment by markbasham** [comment]
I have reduced the spam by only showing the parameters of the changed item, hopefully this is enough as I am wary of turning off all the user feedback when changes are made.

**Comment by aaron-parsons** [comment]
Sounds a reasonable compromise.
