### ISSUE TITLE
Fix issue with opening Savu output Nexus file in Dawn

### ISSUE THREAD

**Issue by nicwade** [DiamondLightSource/Savu#278]
It's really useful to be able to see all information in DAWN when viewing an output data set!!!

**Comment by markbasham** [comment]
Ticket created in DLS jira for this

http://jira.diamond.ac.uk/browse/SCI-5610

**Comment by markbasham** [comment]
It does work in dawn 1.10 though if you want to use it you can use

module load dawn/1.10

This also points out its probably a problem with dawn or the new axis system.

**Comment by markbasham** [comment]
All sorted now, Will be in the next release of dawn(in about 2 weeks) and available through 

module load dawn/snapshot

Now if needed.
