### ISSUE TITLE
Determine why data is passed as a string ('data') to run_process() from plugin_test.py

### ISSUE THREAD

**Issue by nicwade** [DiamondLightSource/Savu#29]

**Comment by markbasham** [comment]
This is a testing thing, but i think it does add confusion, a better approach would be to make a non file backed Data class which can be passed in for this testing scenario.

However this is not a priority, so I'm putting it back to v0.3

**Comment by markbasham** [comment]
Turned out I used this for testing with some of the runner methods, for cheking if the cpu/gpu arguments worked or not, this is no longer required.
