### ISSUE TITLE
Jenkins: _add_extra_dims_to_patterns has gone missing

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#319]
This affects:
savu.test.jenkins.process_list_tests.spectra_tomo_chunking_single_sino_test.SpectraTomoChunkingSingleSinoTes

 and

savu.test.jenkins.process_list_tests.simple_fit_recon_single_sino_test.SimpleFitReconSingleSinoTest.test_process

**Comment by nicwade** [comment]
It was an easy fix, I'd just renamed the function and forgotten to amend it in the Data class. 

simple_fit_recon_single_sino_test.py is now back over to you and it seems to be trying to copy a SINOGRAM pattern from a dataset that doesn't contain it...

**Comment by nicwade** [comment]
Same case for both of these. Do we need to add a no_process_plugin to the pipeline with parameter tuning?
