### ISSUE TITLE
dark/flat field correction  in savu_mpi gets only the first strip for all parallel strips

### ISSUE THREAD

**Issue by rcatwood** [DiamondLightSource/Savu#341]
The result of running savu_mpi with ONLY the flat/dark corrction plugin (and loader and saver) shows the problem that each parallel chunk seems to be corrected by only the top chunk of the flat field. See the repeating time-stamp block in the corrected projection view. 

![screenshot-data browsing - -dls-i12-data-2016-cm14465-3-processing-herculaneum-df_only-20160810134126_61404-tomo_p1_dark_flat_field_correction h5 - dawn science - -home-kny48981-dawn_stable](https://cloud.githubusercontent.com/assets/12137034/17554976/8e3c9bf2-5f05-11e6-9a28-871f68c9761f.png)

See /dls/tmp/kny48981/savu_bug/flat_field_problem

Module: 

 savu/version1(default)

Command: 
savu_mpi ../../rawdata/61404.nxs df_only.savu df_only
Process list:

> > > open df_only.savu
> > > Opening file df_only.savu

 0) NxtomoLoader(savu.plugins.loaders.nxtomo_loader)
   1)                preview : ['620:620+101:1:1', '0:end:1:1', '0:end:1:1']
   2)              data_path : entry1/tomo_entry/data/data
 1) DarkFlatFieldCorrection(savu.plugins.corrections.dark_flat_field_correction)
   1)            in_datasets : []
   2)           out_datasets : []
   3)                pattern : SINOGRAM
 2) Hdf5TomoSaver(savu.plugins.savers.hdf5_tomo_saver)

**Comment by rcatwood** [comment]
@markbasham I don't see how to 'assign' this, is it not visible if its not 'assigned'?

**Comment by nicwade** [comment]
This is now fixed and will be in the new release, hopefully by the end of the week.
