### ISSUE TITLE
dawn_compatible

### ISSUE THREAD

**Issue by srikanthnagella** [DiamondLightSource/Savu#381]
when fftw is installed. savu_config fails and throws up error ImportError: Import by filename is not supported. in paganinfilter has dawn_compatible which causes this error.

**Comment by nicwade** [comment]
Hi Sri,
I've assigned this to Aaron as he has been dealing with DAWN compatibility.  However, we are not having any problems with the configurator.  Do you have any more information so we can re-create the error?   Thanks, Nic.

**Comment by srikanthnagella** [comment]
Currently there are only 2 dawn_compatible annotated filters and they both import pyfftw. My guess is that you don't have pyfftw installed on your system which fails to load this module.

**Comment by nicwade** [comment]
We use PaganinFilter all the time and there is no problem importing and running the plugin.
