### ISSUE TITLE
Make plugin finding for external plugins work with relative paths/ script names only

### ISSUE THREAD

**Issue by markbasham** [DiamondLightSource/Savu#4]

**Comment by markbasham** [comment]
Possibly a $SAVU_USER_PLUGINS location

**Comment by markbasham** [comment]
$SAVU_PLUGIN_PATH is possibly better

**Comment by aaron-parsons** [comment]
Do we have anything for this yet? Useful for licensing issues.

**Comment by markbasham** [comment]
Not yet, but I might take a look

Sent from my HTC

----- Reply message -----

**Comment by markbasham** [comment]
Done now, possibly we could do with a better option based on an env variable as well
