### ISSUE TITLE
Remove local data links in PyfaiAzimuthalIntegrationTestFull

### ISSUE THREAD

**Issue by markbasham** [DiamondLightSource/Savu#40]
There are links to local data in the test, causing it to fail, Disabled for now.

**Comment by markbasham** [comment]
I realise that this is not too sencible as it points at a big dataset.  Might be worth adding a class of tests only to be run at diamond which point at large data.

**Comment by aaron-parsons** [comment]
I can just remove the test. Wasn't ever really a true test anyway...
