### ISSUE TITLE
ValueError: Not a dataset (Not a dataset)

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#440]
When processing Speckle tracking data we get the error:
ValueError: Not a dataset (Not a dataset)
 WE initially thought this was an issue with the datasize/number of nodes, but on trying it with the process list /dls/i13/data/2017/mt18131-1/processing/savu_inputs/savu_processing/TesticleProcessor.nxs, where we do the same thing to two identical datasets, we find that the processing works fine for one dataset, but fails for the second one.

The parameter file for savu_mpi_devel is /dls/i13/data/2017/mt18131-1/processing/savu_inputs/savu_processing/savu_run_parameters.txt

We are likely to hit this problem a lot as we start to process ptychography datasets also.

**Comment by aaron-parsons** [comment]
This still happens when I set the interpolation value to 1. And now I just reproduced it with a NoProcessPlugin.

If you use /dls/i13/data/2017/mt18131-1/processing/savu_inputs/savu_processing/TesticleProcessor2.nxs on the same dataset, you get the log file in:/dls/i13/data/2017/mt18131-1/processing/savu_inputs/savu_processing//20170720132831_aligned_rawdata_testicle2/savu.o1940194

**Comment by nicwade** [comment]
This doesn't work because the input file is a hdf5 file containing multiple datasets.  In Savu you can only have one dataset per hdf5 file but you can link to multiple hdf5 files in a Nexus file.
