### ISSUE TITLE
Fix up the tomo loader class

### ISSUE THREAD

**Issue by markbasham** [DiamondLightSource/Savu#50]
There are quite a few things which could do with a refactor.
1. hard coded strings should be dealt with as statics
2. there are some places where there are multiple locations in the NXtomo where things can be found, they should all be tested, as some files don't contain everything they need.

**Comment by DLSTasktop** [comment]
(Comment from Mark Basham):

This is mainly to get the process working with 4D data now when there are partial issues.

**Comment by DLSTasktop** [comment]
(Comment from Mark Basham):

Loading for 4d data is working as expected now.
