### ISSUE TITLE
Access to TomoPhantom software from SAVU

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/Savu#528]
Integration of the [TomoPhantom](https://github.com/dkazanc/TomoPhantom) package to **Savu**. Tasks to implement: 
- [x] Ability to build the subsets of 3D and 4D phantoms in **TomoPhantom**
- [x] MPI access to the option above in **Savu**
- [x] 2D functionality is fully embedded into **Savu**
- [x] Ability to generate 3D/4D projection data in **TomoPhantom** (related [issue](https://github.com/dkazanc/TomoPhantom/issues/23))
- [x] MPI-specific slicing when creating projection data (create `ModelSinoSub`)
- [ ] **Savu** demo plugins/scripts (as well as tests) how to use **TomoPhantom**
- [ ] Documentation

**Comment by DLSTasktop** [comment]
(Comment from Daniil Kazantsev):

Deployed to some extent. 3D case requires some Savu workarounds
